[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/admin-recreate-user"
  to = "https://dqfyuhwrjozoxadkccdj.supabase.co/functions/v1/admin-recreate-user"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

[[redirects]]
  from = "/api/*"
  to = "https://dqfyuhwrjozoxadkccdj.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
